/* eslint-env browser */
'use strict';

const terms = [
  'Black Lives Matter',
  'LGBT rights',
  'Planned Parenthood',
  'Social Security',
  'better together',
  'climate change',
  'chance',
  'education',
  'equality',
  'fair',
  'families',
  'first responders',
  'foreign aid',
  'future',
  'gay rights',
  'global warming',
  'green energy',
  'healthcare',
  'help',
  'human rights',
  'immigration',
  'infrastructure',
  'innovation',
  'invest',
  'justice',
  'labor',
  'livable wage',
  'middle class',
  'minimum wage',
  'mothers',
  'opportunity',
  'racism',
  'reform',
  'renewable energy',
  'right to choose',
  'security',
  'stronger',
  'our troops',
  'together',
  'veterans',
  'young people'
];

export default terms;
